create table if not exists users
(
    id            bigint generated by default as identity
        constraint "USERS_pkey"
            primary key,
    name          varchar(500) not null,
    date_of_birth date,
    password      varchar(500)
);

create table if not exists account
(
    id            bigint generated by default as identity
        constraint "ACCOUNT_pkey"
            primary key,
    user_id       bigint generated by default as identity
        constraint fk_account_user
            references users,
    balance       numeric(19, 2),
    start_deposit numeric(19, 2)
);

create table if not exists email_data
(
    id      bigint generated by default as identity
        constraint "EMAIL_DATA_pkey"
            primary key,
    user_id bigint generated by default as identity
        constraint fk_email_data_user
            references users,
    email   varchar(200) not null
        unique
);

create table if not exists phone_data
(
    id      bigint generated by default as identity
        constraint "PHONE_DATA_pkey"
            primary key,
    user_id bigint generated by default as identity
        constraint fk_phone_data_user
            references users,
    phone   varchar(13) not null
        unique
);
